<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Các thư viện cũ -->
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.5.2" />
    <PackageVersion Include="Aspire.Hosting.RabbitMQ" Version="13.5.2" />
    <PackageVersion Include="Aspire.Hosting.Redis" Version="13.5.2" />
    <PackageVersion Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.3" />
    <PackageVersion Include="MassTransit.RabbitMQ" Version="9.2.1" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <!-- CÁC THƯ VIỆN MỚI THÊM CHO .NET ASPIRE -->
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="8.2.2" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="8.10.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="8.2.2" />
    <!-- Đã đồng bộ tất cả về 1.11.1 -->
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0" />
    <PackageVersion Include="Yarp.ReverseProxy" Version="2.2.0" />
  </ItemGroup>
</Project>